---

selinux_status:
  - policy: targeted
    state: permissive
  
users:
  - name: xml
    group: chlservices
    gid: 600
    
user_home_path: /home/xml

s3_file_perl_lib: /application/shared/libraries/perl-xerces-lib.tar.gz
s3_file_perl_lib_name: '{{ s3_file_perl_lib | basename }}'

tar_files:
  - "{{ s3_file_perl_lib_name }}"

xerces_paths:
  - /usr/local/lib
  - /usr/local/include

install_watcher_service: true

postfix_main_config_file: main.cf
postfix_config:
  - key: mydomain
    value: companieshouse.gov.uk
  - key: myorigin 
    value: $mydomain
  - key: relayhost
    value: smtp-outbound.sharedservices.aws.internal

postfix_net_config:
  - key: inet_interfaces 
    value: all
  - key: inet_protocols 
    value: ipv4