---
  - name: Deploy XML artifact
    hosts: localhost
    gather_facts: true
    vars:
      ansible_python_interpreter: /usr/local/bin/python3.6
      application_name: "xmlgw"
      home_dir: "/home/xml"
      directories:
        - "DATA" 
        - "MODULES"
        - "htdocs"
    roles:
      - { role: /root/roles/nfs_mounts }
    tasks:
      - name: Download the versioned release artifact from S3
        aws_s3:
          bucket: "{{ s3_bucket_releases }}"
          object: "chl-perl/{{ application_name }}/{{ application_name }}-{{ version }}.zip"
          dest: "/tmp/{{ application_name }}-{{ version }}.zip"
          mode: get

      - name: Create temporary app folder for unzip
        file:
          path: "/tmp/{{ application_name }}-{{ version }}"
          state: directory
      
      - name: Unarchive the artifact into its own folder
        unarchive:
          remote_src: yes
          src: "/tmp/{{ application_name }}-{{ version }}.zip"
          dest: "/tmp/{{ application_name }}-{{ version }}"
      
      - name: Copy folders to relevant locations
        vars:
          ansible_python_interpreter: /usr/bin/python2.6
        copy:
          src: "/tmp/{{ application_name }}-{{ version }}/{{ item }}"
          dest: "{{ home_dir }}/"
          mode: preserve
          owner: "{{ home_dir | basename }}"
          remote_src: yes
        loop: "{{ directories }}"
      
      - name: Make sure config.pm directory exists
        file:
          path: "{{ home_dir }}/config/My"
          state: directory
          recurse: yes
          mode: '0755'

      - name: Download environment config.pm file from S3
        aws_s3:
          bucket: "{{ s3_bucket_configs }}"
          object: "chl-{{ application_name }}-configs/{{ heritage_environment }}/{{ application_name|upper }}Config.pm"
          dest: "{{ home_dir }}/config/My/{{ application_name|upper }}Config.pm"
          mode: get

      - name: Change config.pm owner and permissions
        ansible.builtin.file:
          path: "{{ home_dir }}/config/My/{{ application_name|upper }}Config.pm"
          owner: xml
          group: chlservices
          mode: '0755'
      
      - name: Cleanup install files
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - "/tmp/{{ application_name }}-{{ version }}"
          - "/tmp/{{ application_name }}-{{ version }}.zip"

      - name: Ensure apache config files are all owned and permissions are set correctly
        ansible.builtin.file:
          path: "{{ item }}"
          owner: xml
          group: chlservices
          mode: '0644'
        loop:
          - /etc/httpd/conf/httpd.conf
          - /etc/httpd/conf/startup.pl
          - /etc/httpd/conf.d/perl.conf

      - name: Make sure Apache is started
        service:
          name: "httpd"
          state: restarted
          enabled: yes