---
dependencies: []

galaxy_info:
  role_name: centos6-base-repo
  author: Will Watters
  description: Centos 6 base repo EOL RPM fix
  company: "Kainos"
  license: 
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 6
