---
groups:
  - name: chlservices
    gid: 600

s3_bucket: development-eu-west-2.resources.ch.gov.uk
s3_files_oracle: /packages/oracle/oracle-database-10.2.0.tar.gz
s3_files_oracle_name: oracle-database-10.2.0.tar.gz

s3_files_oracle_basic_rpm: /packages/oracle/oracle-instantclient11.2-basic-11.2.0.2.0.x86_64.rpm
s3_files_oracle_devel_rpm: /packages/oracle/oracle-instantclient11.2-devel-11.2.0.2.0.x86_64.rpm
s3_files_oracle_sqlplus_rpm: /packages/oracle/oracle-instantclient11.2-sqlplus-11.2.0.2.0.x86_64.rpm
s3_files_oracle_basic_rpm_name: oracle-instantclient11.2-basic-11.2.0.2.0.x86_64.rpm
s3_files_oracle_devel_rpm_name: oracle-instantclient11.2-devel-11.2.0.2.0.x86_64.rpm
s3_files_oracle_sqlplus_rpm_name: oracle-instantclient11.2-sqlplus-11.2.0.2.0.x86_64.rpm

env_var:
   - export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib/
   - export TNS_ADMIN=/usr/lib/oracle/11.2/client64/lib/

ld_so_conf:
    - /usr/lib/oracle/11.2/client64/lib/
    - /usr/local/lib

perl_binaries:
  - /usr/local/lib64/perl5 
  - /usr/local/share/perl5 
  - /usr/lib64/perl5/vendor_perl 
  - /usr/share/perl5/vendor_perl 
  - /usr/lib64/perl5 
  - /usr/share/perl5

http_conf: /etc/httpd/conf/httpd.conf

user_home_path_content:
  - DATA
  - MODULES
  - htdocs
  - config

user_home_path_content_delete:
  - DATA
  - MODULES
  - htdocs
  - config
  - usr

files_to_remove: 'oracle-instantclient*,*.tar.gz,get-pip*,Python*'